# submit
cd /scratch/gpfs/ar8787/groupdata2/india_forest_land/C_Programs/_vcf_10_augsyth/median_filter/by_state/batch
sbatch sate_22.sbatch
sbatch sate_28.sbatch
sbatch sate_20.sbatch
sbatch sate_24.sbatch
sbatch sate_9.sbatch
sbatch sate_11.sbatch
sbatch sate_29.sbatch
sbatch sate_30.sbatch
sbatch sate_21.sbatch
